Main:
    HttpPort: 8082
    HttpsOn: false
    Domain: ""
    HttpsPort: 443
    PubDir: "static"
    ViewDir: "view/default"
    Youdb: "mydata.db"
    CookieSecure: false
    CookieHttpOnly: true
    OldSiteDomain: ""
    TLSCrtFile: ""
    TLSKeyFile: ""
Site:
    Name: "Kani"
    Desc: "Kani Server"
    AdminEmail: ""
    MainDomain: "http://127.0.0.1:8082"
    MainNodeIds: "1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20"
    TimeZone: 8
    HomeShowNum: 20
    PageShowNum: 20
    TagShowNum: 20
    CategoryShowNum: 20
    TitleMaxLen: 180
    ContentMaxLen: 9000
    PostInterval: 60
    CommentListNum: 100
    CommentInterval: 20
    Authorized: false
    RegReview: false
    CloseReg: false
    AutoDataBackup: false
    AutoGetTag: true
    GetTagApi: "http://youbbs.sinaapp.com/fencigoapi.php"
    QQClientID: 0
    QQClientSecret: ""
    WeiboClientID: 0
    WeiboClientSecret: ""
    UploadSuffix: ""
    UploadImgOnly: false
    UploadImgResize: false
    UploadMaxSize: 50
    QiniuAccessKey: ""
    QiniuSecretKey: ""
    QiniuDomain: ""
    QiniuBucket: ""
    UpyunDomain: ""
    UpyunBucket: ""
    UpyunUser: ""
    UpyunPw: ""
    SMTPServer: ""
    SMTPPort: 0
    SMTPUser: ""
    SMTPPassword: ""
    SMSURL: ""
    SMSAppKey: ""
    SMSAppSecret: ""
